#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_homepage:
  path: /
  controller: App\Controller\HomeController::index
app_list:
  path: /produit/create
  controller: App\Controller\ProductController::create
  methods: ['GET','POST']
app_product_show:
  path: /produit/{slug}
  controller: App\Controller\ProductController::show
  requirements:
    slug: '[a-z0-9\-]+'
  methods: ['GET']
